server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/practica_nro05_06
    username: practica_nro05_06
    password: practica_nro05_06
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
jwt:
  secret: "practica_nro05_06_secret_key_2026"
  expiration: 86400000
